### ISSUE TITLE
对url检查不严谨存在文件读取漏洞

### ISSUE THREAD

**Issue by DGPassbyA** [pcrbot/pagecut#1]
项目存在任意文件读取漏洞，原因是对传入url协议的判断不严谨
```python
    if 'http://' not in path and 'https://' not in path:
        path='http://'+path
```
构造`file://xxxx?http://`即可绕过检查
![利用](https://s2.loli.net/2022/03/27/DRAzqr3cQ71sdFn.png)
修复建议：改用startswith检查url

**Comment by G41mywaifu** [comment]
确实  感谢大佬的建议
